export const SET_MODAL_ATTRIBUTES = 'SET_MODAL_ATTRIBUTES'
export const SET_MODULE_FILE = 'SET_MODULE_FILE'
export const SET_LOCKER_FILES = 'SET_LOCKER_FILES'
export const CLEAR_PENDING_LOCKER_FILES = 'CLEAR_PENDING_LOCKER_FILES'
